### PR TITLE
Add single-producer single-consumer queue

### PR DESCRIPTION
**Pull request by bartoszmodelski**
I have a few lock-free structures to donate (spsc queue, mpmc queue, multi-queue, spmc queue, spmc stack). Starting with the simplest one - single-producer single-consumer queue. 

### Structure

Enqueue inserts element into the structure, while dequeue removes in FIFO order. The structure is safe because, from the perspective of other operation, enqueuer operates only on [tail, head + size) part of the array, whereas dequeuer on [head, tail). Sample state:
```
| Index          | 0    | 1      | 2      | 3    |
| -------------- | ---- | ------ | ------ | ---- |
| Array (sz = 4) | None | Some A | Some B | None |
| Head           |      | X      |        |      |
| Tail           |      |        |        | X    |
| Enq. range     | X    |        |        | X    |
| Deq. range     |      | X      | X      |      |
```
### Testing

I've created a few simple tests, one with two threads and 100k items being transferred. I'd be happy to write some DSCheck tests (https://github.com/sadiqj/dscheck).

### Possible extensions: 
* Automatic resizing is a little awkward but possible. Natural place to grow the array would be in the insertion function. However, enqueuer cannot remove elements from the existing array in SPSC, so I guess we'd be end up with some sort of list of arrays. 
* Aligning the indices with cache lines significantly improves the performance (see https://github.com/anmolsahoo25/aligned_int).

### CODE REVIEW

**Comment by lyrm** [comment]
Hi! 
I have reviewed your code and added tests. Also for uniformity with the other queues in this repo, I renamed `enqueue` to `push` and `dequeue` to `pop` and made a small change in `enqueue` to raise a `Full` exception when the queue is full instead of returning a boolean. 

Is it ok with you if I push directly on your repo to update this PR ? I am asking because I will be pushing on your `main` branch.

**Comment by bartoszmodelski** [comment]
Hi! 

Thanks for review!

Pushing onto my main branch is fine. I assume you would not have permission to do this now, so I added you as a collaborator to my fork.

**Comment by lyrm** [comment]
Hi @bartoszmodelski,  
Could you resend me the invitation ? It seems it had an expiration date !
Sorry about that !

**Comment by bartoszmodelski** [comment]
Hi @lyrm, no worries. Just added you, let me know if that works.

**Comment by bartoszmodelski** [comment]
hi @lyrm, is it good to merge?

**Comment by lyrm** [comment]
Hi @bartoszmodelski, I did not try any dscheck tests for this queue. Did you ? (even if we can not add them here right now)

**Comment by bartoszmodelski** [comment]
Tried just now, looks good. 

[test_spsc_queue.txt](https://github.com/ocaml-multicore/lockfree/files/9776329/test_spsc_queue.txt)

**Pull request merged**
