### PR TITLE
Remove virtual library over atomic

### PR DESCRIPTION
**Pull request by lyrm**
In answer to issue #44.

I replaced the virtual library over `Atomic` with copy actions in `dscheck` dune rules as suggested by @talex5 in #44. I  also had to refactored the test directory as multiple data structures require the `Backoff` module and it was interfering with the fact that multiple dune rules can not use the same module. 

Also, it appears that `michael_scott_queue` and `treiber_stack` tests with `dscheck` are actually not running properly in the main branch as the virtual `Atomic` lib is not used. Once I correct that, it appears that some tests are overloading the memory most likely because there are too many paths to explore for `dscheck`.  I either simplified the tests or removed them (there are kind of redundant with previous ones).

### CODE REVIEW

**Comment by talex5** [comment]
> I also had to refactored the test directory as multiple data structures require the Backoff module and it was interfering with the fact that multiple dune rules can not use the same module.

I had the same problem in Eio, but it turns out that using the plural forms (e.g. `executables` rather than several `executable` stanzas) solves it.

**Comment by lyrm** [comment]
Oh, interesting ! I will remember that ! Thanks.

I think sorting the tests by data structures is pretty convenient as it enables to easily run tests for a single data structure but if anyone is against it, I will be happy to discuss it.

**Review by bartoszmodelski — APPROVED** [review]
Looks good to me. Perhaps I'd add a little comment in `atomic.ml` or markdown file in `test/` explaining that we copy-over implementations in order to shadow part of stdlib for dscheck tests.

**Comment by lyrm** [comment]
Thanks for your review. That's a very good idea, so I just did it. Does it match what you had in mind ?

**Comment by bartoszmodelski** [comment]
exactly that, thanks

**Pull request merged**
